name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    restart: unless-stopped
    depends_on:
      - redis
      - database
    healthcheck:
      disable: false
    # ports:
    #   - 2283:2283
    volumes:
      - ${LIBRARYFOLDER}:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    labels:
      traefik.enable: true
      traefik.http.routers.immich.tls: true
      traefik.http.routers.immich.rule: Host("immich.${URL}")
      traefik.http.services.immich.loadbalancer.server.port: 2283
      glance.name: Immich
      glance.id: immich
      glance.icon: di:immich
      glance.url: https://immich.${URL}
      glance.description: Local Photo Library
      glance.category: media
    networks:
      - frontbridge
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    restart: unless-stopped
    healthcheck:
      disable: false
    volumes:
      - model-cache:/cache
    labels:
      glance.name: Machine Learning
      glance.parent: immich
      glance.category: media
    networks:
      - frontbridge
  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8@sha256:81db6d39e1bba3b3ff32bd3a1b19a6d69690f94a3954ec131277b9a26b95b3aa
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
    labels:
      glance.name: Redis
      glance.parent: immich
      glance.category: media
    networks:
      - frontbridge
  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - ${DOCKERFOLDER}/immich/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
      DB_STORAGE_TYPE: HDD
    networks:
      - frontbridge
  immichframe:
    container_name: immichframe
    image: ghcr.io/immichframe/immichframe:latest
    restart: unless-stopped
    ports:
      - 8042:8080
    depends_on:
      - immich-server
    volumes:
      - ${DOCKERFOLDER}/immich/frame:/app/Config
    environment:
      TZ: America/Toronto
    labels:
      traefik.enable: true
      traefik.http.routers.immichframe.tls: true
      traefik.http.routers.immichframe.rule: Host("immichframe.${URL}")
      traefik.http.services.immichframe.loadbalancer.server.port: 8080
      glance.name: ImmichFrame
      glance.icon: di:immich-frame-light
      glance.url: https://immichframe.${URL}
      glance.description: Local Photo Library Slideshow
      glance.category: media
    networks:
      - frontbridge

networks:
  frontbridge:
    external: true
  backbridge:
    external: true
